### ISSUE TITLE
Support block elements 2580…9F in Symbol2

### ISSUE THREAD

**Issue by Mercury13** [notofonts/symbols#70] opened 2023-05-23 04:11 UTC
**Is your feature request related to a problem? Please describe.**
Symbol2 supports Symbols for legacy computing. Those symbols include sextant fills, and some of them (e.g. 258C) are taken from existing BMP block.

**Describe the solution you'd like**
Support 2580…9F, **with the same character cell size**. That’s probably enough. None of known legacy systems supports both sextants and box drawing.

**Describe alternatives you've considered**
1. Move all pseudographics Symbol → Symbol2. That’s IMHO extraneous, and they do not tile together (Symbol’s character cell is taller), so they should be redrawn to match size.
2. Use Symbol for some blocks, and Symbol2 for others. It’s just hard, and, again, they do not tile together.
3. Move symbols for legacy computing to Symbol. Again, they do not tile and should be redrawn.

**Additional context**
![image](https://github.com/notofonts/symbols/assets/10164882/9d659eb1-2f0c-45d3-9319-43a14145bef4)
Block sextant-351 should have been afterwards, between 35 and 352… But it’s already in BMP, 258C.

(not related to my Unicodia, it’s just better for general usability of those symbols)

**Comment by simoncozens** [comment] 2023-06-27 11:16
Duplicate of #26.

**Closed by simoncozens** 2023-06-27 11:16 UTC
Labels: Triaged
